# Generated by Django 5.2.7 on 2025-11-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
