# Generated by Django 5.2.7 on 2025-11-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_tweet_dislikes_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
